name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compile Java code
      run: |
        if (Test-Path src/) {
          cd src/
          $javaFiles = Get-ChildItem -Filter *.java
          if ($javaFiles) {
            javac *.java
            if ($LASTEXITCODE -ne 0) {
              Write-Error "Compilation failed"
              exit 1
            }
          } else {
            echo "No Java files to compile."
          }
        } else {
          echo "src/ directory does not exist."
        }
      shell: pwsh

    - name: Run Java main classes (if any)
      run: |
        cd src
        foreach ($file in Get-ChildItem -Filter *.class) {
          $className = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
          echo "Running $className"
          java $className
        }
      shell: pwsh
