name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed and new Java files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: |
          src/**/*.java

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compile changed and new Java files
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        $changedFiles = "${{ steps.changed-files.outputs.all_changed_files }}"
        $files = $changedFiles -split ' '
        Write-Host "Files to compile:"
        foreach ($file in $files) {
          Write-Host "- $file"
        }
        
        foreach ($file in $files) {
          if ($file -like "*.java") {
            Write-Host "Compiling: $file"
            javac "$file"
            if ($LASTEXITCODE -ne 0) {
              Write-Error "Compilation failed for $file"
              exit 1
            }
          }
        }
      shell: pwsh

    - name: Run compiled Java files
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        $changedFiles = "${{ steps.changed-files.outputs.all_changed_files }}"
        $files = $changedFiles -split ' '
        foreach ($file in $files) {
          if ($file -like "*.java") {
            $fileName = [System.IO.Path]::GetFileNameWithoutExtension($file)
            $dir = [System.IO.Path]::GetDirectoryName($file)
            if ($dir) {
              Push-Location $dir
            }
            Write-Host "Running: $fileName"
            java $fileName
            if ($dir) {
              Pop-Location
            }
          }
        }
      shell: pwsh

    - name: No Java files changed
      if: steps.changed-files.outputs.any_changed == 'false'
      run: echo "No Java files were changed or added in this push."
