name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compile Java code
      run: |
        if (Test-Path src/) {
          cd src/
          if (Get-ChildItem -Filter *.java) {
            javac *.java
          } else {
            echo "No Java files to compile."
          }
        } else {
          echo "src/ directory does not exist."
        }
      shell: pwsh

    - name: Run Java tests (if any)
      run: |
        echo "Add your test commands here"
